In [31]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

## Dados

In [32]:
X = np.array([
        np.array([
        1, 1, 1, 1,
        1, 0, 0, 0,
        1, 0, 0, 1,
        1, 1, 1, 1
        ]),
        np.array([
        1, 1, 1, 1,
        1, 0, 0, 1,
        1, 0, 0, 1,
        1, 1, 0, 1
        ]),
        np.array([
        1, 1, 1, 1,
        1, 0, 0, 1,
        1, 0, 0, 1,
        1, 0, 1, 1
        ]),
      np.array([
        1, 0, 1, 1,
        1, 0, 0, 1,
        1, 0, 0, 1,
        1, 0, 1, 1
        ]),
    
    np.array([
        1, 0, 1, 1,
        1, 0, 0, 1,
        1, 0, 1, 1,
        1, 0, 1, 1
        ]),
     np.array([
        1, 1, 0, 1,
        1, 0, 0, 1,
        1, 0, 0, 1,
        1, 0, 1, 1
        ]),

        np.array([
        1, 0, 0, 1,
        0, 1, 1, 0,
        0, 1, 1, 0,
        1, 0, 0, 1
        ]),
        np.array([
        0, 0, 0, 1,
        0, 1, 1, 0,
        0, 1, 1, 0,
        1, 0, 0, 1
        ]),
        np.array([
        1, 0, 0, 1,
        0, 1, 1, 0,
        0, 1, 0, 0,
        1, 0, 0, 1
        ]),
      np.array([
        0, 0, 0, 1,
        0, 1, 1, 0,
        0, 1, 0, 0,
        1, 0, 0, 1
        ]),
       np.array([
        1, 0, 0, 1,
        0, 1, 1, 0,
        0, 1, 0, 0,
        0, 0, 0, 1
        ]),
       np.array([
        1, 0, 0, 1,
        0, 0, 1, 0,
        0, 1, 0, 0,
        1, 0, 0, 1
        ])
    ])

y = np.array([
    np.array([1, 0]),
    np.array([1, 0]),
    np.array([1, 0]),
    np.array([1, 0]),
    np.array([1, 0]),
    np.array([1, 0]),
    np.array([0, 1]),
    np.array([0, 1]),
    np.array([0, 1]),
    np.array([0, 1]),
    np.array([0, 1]),
    np.array([0, 1])
    ])





In [33]:
print("X:")
print(X)
print("\n")
print("Y:")
print(y)

X:
[[1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 1]
 [1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 1]
 [1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1]
 [1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1]
 [1 0 1 1 1 0 0 1 1 0 1 1 1 0 1 1]
 [1 1 0 1 1 0 0 1 1 0 0 1 1 0 1 1]
 [1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1]
 [0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1]
 [1 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1]
 [0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1]
 [1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1]]


Y:
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


## Dividir os dados em treino e teste

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25, random_state=42)

In [35]:
print(X_train)

[[1 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1]
 [1 1 0 1 1 0 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 1]
 [1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1]
 [1 0 1 1 1 0 0 1 1 0 1 1 1 0 1 1]
 [0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1]
 [1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1]
 [1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1]]


In [36]:
print(X_test)

[[1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1]
 [0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1]
 [1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 1]]


### Funcoes auxiliares

In [8]:
#show loss curve of a model
def show_loss_curve(model):
    
    loss_curve =  model.loss_curve_
    plt.plot(loss_curve)
    plt.axis(True)
    plt.show()

In [15]:
def get_score(model,X,y):
    y_pred = model.predict(X)
    class_= classification_report(y, y_pred)
    print("Classification Report:")
    print("\n")
    print(class_)

## Definir o modelo

In [20]:
def run_model(X,y,activation_fun,r,alpha,max_iters, do_shuffle):
    
    best_loss = 1
    while (best_loss) > 0.1:
        model = MLPClassifier(  solver='sgd',
                                activation=activation_fun,
                                learning_rate_init=r,
                                momentum=alpha,
                                max_iter=max_iters,
                                shuffle=do_shuffle,
                                tol=1e-6,
                                hidden_layer_sizes=(2,),
                                verbose=False)
        
        model.fit(X, y)
        best_loss = model.best_loss_
    
    return model
        

In [80]:
model = run_model(X=X_train,y=y_train,activation_fun='relu',r=0.05,alpha=1.,max_iters=100000, do_shuffle=False)

In [81]:
#show_loss_curve(model)
get_score(model,X_test,y_test)
n_iter = model.n_iter_
print(n_iter)


Classification Report:


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

   micro avg       1.00      1.00      1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3
 samples avg       1.00      1.00      1.00         3

83
